### ISSUE TITLE
Not compile linux mint/ubuntu 20.04

### ISSUE THREAD

**Issue by sirlordt** [gdt050579/AppCUI#287]
**Desktop (please complete the following information):**
 - OS: Linux
 - AppCUI Version: Last cloned github ( March 2/22 )

**Describe the bug**
Look the image

**To Reproduce**
Steps to reproduce the behavior (example):
./build.sh

**Expected behavior**
Compile library and demos

**Screenshots**

![image](https://user-images.githubusercontent.com/4441192/156479020-729abf77-df03-40bb-87ee-aaef47ae2fb7.png)

![image](https://user-images.githubusercontent.com/4441192/156479408-ff510536-e44b-4eef-8224-f99c0f690be8.png)

**Additional context**
Linux mint is based in ubuntu 20.04

**Comment by gdt050579** [comment]
Thanks for reporting this to us.
Is it possible to provide GCC version as well ?

**Comment by xTachyon** [comment]
Should be fixed. Could you try now?

**Comment by sirlordt** [comment]
Thanks excelent now compile!!!!. Excelent project!!
