### ISSUE TITLE
Not run in real tty with not XWindows, With SDL2 enabled.

### ISSUE THREAD

**Issue by sirlordt** [gdt050579/AppCUI#289]
**Desktop (please complete the following information):**
 - OS: Linux Mint/Ubuntu 20.04
 - AppCUI Version: Current from git repo (03/03/22).

**Describe the bug**
When the try to run the examples in a real tty (Press ctrl+alt+f1), the examples not run, not error messages, no core dump, not nothing, junt run the example and out again to system shell. I suspect from SDL2 library.

**To Reproduce**
Steps to reproduce the behavior (example):
1. In XWindows press (ctrl+alt+f1) if your are in vmware workstation press ctrl+alt+space bar+f1.
2. The real tty1 must be show, make login and password, move to folder example.
3. Try to run any example and not work.

**Expected behavior**
The example must be run and work.

**Screenshots**

**Additional context**
Is important to run because a i need run console app in real tty and not xwindows terminals, used a lot in cloud servers.

**Comment by xTachyon** [comment]
It sounds like you want to run with the ncurses backend, which seems to have some issues right now. I'll look at it more tomorrow.

**Comment by xTachyon** [comment]
Should be fixed in #291 . Try compiling with `-DAPPCUI_HAS_SDL=0` while having ncurses installed.

**Comment by sirlordt** [comment]
Excelent!!!. Now run in tty. But look different.

![image](https://user-images.githubusercontent.com/4441192/156818619-4ff256f8-efe1-4075-ba8e-ad1623839f96.png)
 
Midnight commander look right

![image](https://user-images.githubusercontent.com/4441192/156818963-9f7da560-293c-4be8-b267-b0a9766183e5.png)

**Comment by gdt050579** [comment]
It looks like not unicode characters are supported by ncurses. We use `mv_add`  in the backend to draw characters and based on the documentation it looks like only some unicode characters can be displayes: https://docs.oracle.com/cd/E36784_01/html/E36880/mvaddwch-3curses.html
For example, only single line boxes seems to be possible, double line is not. 
We will further investigate --> if there is no work around we will probably add some sort of translation (double line converted automatically into single line, block characters into spaces, etc).

**Comment by gdt050579** [comment]
Also --> from Debian documentation:
https://manpages.debian.org/testing/ncurses-doc/mvadd_wch.3ncurses.en.html
`In this implementation, the Unicode values are used instead of the terminal description's acsc mapping as discussed in ncurses(3X) for the environment variable NCURSES_NO_UTF8_ACS. In contrast, for the same cases, the line-drawing characters described in curs_addch(3X) will use only the ASCII default values.`
and
`[NCURSES_NO_UTF8_ACS]()
       During initialization, the ncurses library  checks  for  special  cases
       where VT100 line-drawing (and the corresponding alternate character set
       capabilities) described in  the  terminfo  are  known  to  be  missing.
       Specifically,  when  running  in  a  UTF-8  locale,  the  Linux console
       emulator and the GNU screen program ignore these.  Ncurses  checks  the
       TERM  environment  variable  for  these.   For other special cases, you
       should set this environment variable.  Doing this tells ncurses to  use
       Unicode values which correspond to the VT100 line-drawing glyphs.  That
       works for the special cases cited, and is likely to work  for  terminal
       emulators.`
Can you check if the environment variable is set on your TTY ?
We will also investigate if we can change this behavior ourselves.

**Comment by xTachyon** [comment]
Could you make another issue with this?
