### ISSUE TITLE
With not SLD2 all compile/link fine. But later cannot run any example

### ISSUE THREAD

**Issue by sirlordt** [gdt050579/AppCUI#290]
**Desktop (please complete the following information):**
 - OS: Linux Mint/Ubuntu 20.04
 - AppCUI Version: Current version of the git (03/03/22)

**Describe the bug**
I made changes in AppCUI/AppCUI/CMakeList.txt to force not detect SDL2. Everything compile/link fine. But later the examples not run. Not error message, Not core dump, No nothing, Even in a real tty (Press ctrl+alt+f1) has the same behavior. 

**To Reproduce**
1. Change the file AppCUI/AppCUI/CMakeList.txt, put in comment the lines 25 to 29, save the file.
2. Run ./build.sh
3. All compile/link fine.
4. Try to run any example in /bin/buttons. Nothing happen, no errors, no core dump.

**Expected behavior**
Run the examples.

**Screenshots**
![image](https://user-images.githubusercontent.com/4441192/156652518-4f7599ca-7d00-4486-92e7-d70f5b4a25b2.png)

![image](https://user-images.githubusercontent.com/4441192/156652584-93738dcb-9b50-47ce-a2be-44d533b583d9.png)

**Additional context**

**Comment by xTachyon** [comment]
I think this is the same issue as #289 which is fixed. Could you try again?

**Comment by sirlordt** [comment]
Yes now work!!! but look different in real tty

![image](https://user-images.githubusercontent.com/4441192/156819519-81b4609c-f4b1-44c1-a061-435f586b622c.png)

Midnight commander look ok in real tty

![image](https://user-images.githubusercontent.com/4441192/156819590-242ee779-9273-4e87-b08f-5612ae6be38b.png)
