### ISSUE TITLE
Running very slowly under Windows

### ISSUE THREAD

**Issue by pgmwizard** [gdt050579/AppCUI#426]
**Desktop (please complete the following information):**
 -OS: Windows11 window Terminal
 - AppCUI Version [1.201.0]

**Describe the bug**
Running very slowly under Windows

**Comment by gheorghitamutu** [comment]
Hello,
At first glance, Windows Terminal seems to use https://learn.microsoft.com/en-us/windows/console/ecosystem-roadmap, more specifically Console APIs - https://learn.microsoft.com/en-us/windows/console/classic-vs-vt.

We'll look into adding support for these new APIs. Unfortunately this will take a bit longer:)

Until then I'd recommend using old cmd.exe to run AppCUI (and AppCUI examples) from.
